# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/AnalyzingNeuralTimeSeries-Python',
                'doc_host': 'https://agencyenterprise.github.io',
                'git_url': 'https://github.com/agencyenterprise/AnalyzingNeuralTimeSeries-Python',
                'lib_path': 'AnalyzingNeuralTimeSeries_Python'},
  'syms': { 'AnalyzingNeuralTimeSeries_Python.core': { 'AnalyzingNeuralTimeSeries_Python.core.foo': ( 'core.html#foo',
                                                                                                      'AnalyzingNeuralTimeSeries_Python/core.py')}}}
